### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by leskal**

### CODE REVIEW

**Comment by dragonpt** [comment]
great typo find..
its  WIND now

**Comment by leskal** [comment]
I am living in Greece, i know tge names of carrier

**Comment by leskal** [comment]
Wind has buy Q-TELECOM buy the company remains as it was

**Comment by dragonpt** [comment]
the new convention is 

numeric="20209" spn="WIND GR"
numeric="20210" spn="WIND GR"

**Comment by leskal** [comment]
No, its wrong

**Comment by leskal** [comment]
https://www.wind.gr/en/q/support/settings/

**Comment by dragonpt** [comment]
http://www.apnsettings.org/greece/wind-apn-settings-iphone/

And OEMs are doing 20209 as WindGR now

Q-Mobile was the 4th Greek mobile operator but now it's a subsidiary of Wind
http://wiki.apnchanger.org/Greece#Wind_.281.29

And thats just for the display name.. useful indeed

**Comment by leskal** [comment]
as i mention before, wind has buy q some years ago but the name remains

**Comment by leskal** [comment]
official settings from wind gr!!!!!!!!!

https://www.wind.gr/files/1/wind_v2/devices/PDF/Android_OS_Terminals_new.pdf

**Pull request merged**
